version: '2.3'

services:

  postgres:
    container_name: postgres
    image: postgres:10.4-alpine
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=xxx
      - POSTGRES_PASSWORD=xxx
      - POSTGRES_DB=product_carpet-dev
    
    ports: 
      - '5433:5432' # expose ports - HOST:CONTAINER
    
  carpet-service:
    container_name: carpet-service
    # build: ./CarpetBackend/
    image: sdudu/carpet-service:1.0.8
    ports:
      - '80:8000' # expose ports - HOST:CONTAINER
    environment:
      - LOG_PATH=/var/log
      - APP_NAME=carpet-service
      - POSTGRES_USERNAME=xxx
      - POSTGRES_PASSWORD=xxx
      - POSTGRES_DATABASE=product_carpet-dev
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_PROTOCOL=postgres
    depends_on:
      - postgres
    links:
      - postgres
    command: [ "npm", "run", "start"]

  carpet-webapp:
    container_name: carpet-webapp
    # build: ./CarpetWebApp/
    image: sdudu/carpet-webapp:1.0.9
    ports:
      - '80:5000'
    environment:
      - REACT_APP_DUDU=dudu
      - NODE_ENV=${NODE_ENV}
      - REACT_APP_BASE_URL=carpet-service
    depends_on:
      carpet-service:
        condition: service_started
    links:
      - carpet-service